import React, { useState } from "react";
import { A2MapViewer, type A2MapSpec, type A2MapEvent } from "../src/index.js";

/**
 * Example 3: Agent Generative UI & Bidirectional Loop
 * Demonstrates AI-driven overlay widgets (Legends, Metrics Cards, Action Panels),
 * and the reactive feedback loop where user actions trigger state evolutions.
 */
export const AgentGenerativeUIExample: React.FC = () => {
  const [step, setStep] = useState<"initial" | "analyzed">("initial");

  const initialSpec: A2MapSpec = {
    version: "1.0",
    canvas: {
      baseStyle: "satellite",
      camera: {
        center: [139.69, 35.68],
        zoom: 12,
        pitch: 35,
        animation: "flyTo",
      },
      controls: { navigation: true, scale: true },
    },
    layers: [
      {
        id: "target-region",
        type: "fill",
        source: {
          type: "geojson",
          data: {
            type: "Feature",
            properties: { label: "Candidate Site #402" },
            geometry: {
              type: "Polygon",
              coordinates: [
                [
                  [139.67, 35.66],
                  [139.71, 35.66],
                  [139.71, 35.69],
                  [139.67, 35.69],
                  [139.67, 35.66],
                ],
              ],
            },
          },
        },
        style: {
          color: "#3b82f6",
          strokeColor: "#60a5fa",
          strokeWidth: 4,
          opacity: 0.3,
        },
      },
    ],
    widgets: [
      {
        id: "site-legend",
        type: "legend",
        position: "bottom-left",
        title: "Classification",
        items: [{ label: "Candidate Site (1,240 ha)", color: "#3b82f6" }],
      },
      {
        id: "metrics-overview",
        type: "metrics_card",
        position: "top-left",
        title: "Site Spatial Evaluation",
        metrics: [
          { label: "Total Area", value: "1,240", unit: "ha" },
          { label: "Canopy Density", value: "78.4", unit: "%" },
          { label: "Risk Index", value: "Low", trend: "up" },
        ],
      },
      {
        id: "agent-actions",
        type: "action_panel",
        position: "bottom-right",
        title: "AI Agent Assistant",
        description: "Review spatial metrics and trigger simulated pipeline steps.",
        actions: [
          {
            id: "run-leakage-buffer",
            label: "Calculate 5km Buffer Zone",
            icon: "⚡",
            variant: "primary",
          },
        ],
      },
    ],
  };

  const analyzedSpec: A2MapSpec = {
    ...initialSpec,
    canvas: {
      ...initialSpec.canvas,
      camera: {
        center: [139.69, 35.68],
        zoom: 11,
        pitch: 45,
        bearing: 15,
        animation: "flyTo",
      },
    },
    layers: [
      ...(initialSpec.layers || []),
      // New buffer layer generated by the agent
      {
        id: "buffer-zone",
        type: "line",
        source: {
          type: "geojson",
          data: {
            type: "Feature",
            properties: { label: "5km Buffer Zone" },
            geometry: {
              type: "Polygon",
              coordinates: [
                [
                  [139.63, 35.63],
                  [139.75, 35.63],
                  [139.75, 35.72],
                  [139.63, 35.72],
                  [139.63, 35.63],
                ],
              ],
            },
          },
        },
        style: {
          strokeColor: "#f59e0b",
          strokeWidth: 3,
          dashArray: [2, 2],
        },
      },
    ],
    widgets: [
      {
        id: "site-legend",
        type: "legend",
        position: "bottom-left",
        title: "Classification",
        items: [
          { label: "Candidate Site (1,240 ha)", color: "#3b82f6" },
          { label: "5km Buffer Zone", color: "#f59e0b" },
        ],
      },
      {
        id: "metrics-overview",
        type: "metrics_card",
        position: "top-left",
        title: "Buffer Pipeline Completed",
        metrics: [
          { label: "Primary Area", value: "1,240", unit: "ha" },
          { label: "Buffer Extent", value: "3,890", unit: "ha" },
          { label: "Eligibility", value: "98.2", unit: "%" },
        ],
      },
      {
        id: "agent-actions",
        type: "action_panel",
        position: "bottom-right",
        title: "Pipeline Completed",
        description: "Buffer calculated successfully. Ready to export findings.",
        actions: [
          {
            id: "export-report",
            label: "Generate Audit Summary",
            icon: "📄",
            variant: "primary",
          },
          {
            id: "reset-state",
            label: "Reset Map",
            variant: "ghost",
          },
        ],
      },
      {
        id: "success-banner",
        type: "banner",
        position: "top-center",
        message: "✓ 5km Buffer Zone and eligibility metrics computed.",
        level: "success",
        durationMs: 4000,
      },
    ],
  };

  const handleEvent = (event: A2MapEvent) => {
    if (event.type === "widget_action") {
      if (event.actionId === "run-leakage-buffer") {
        setStep("analyzed");
      } else if (event.actionId === "reset-state") {
        setStep("initial");
      } else if (event.actionId === "export-report") {
        alert("Report exported successfully!");
      }
    }
  };

  return (
    <div style={{ width: "100%", height: "100%" }}>
      <A2MapViewer spec={step === "initial" ? initialSpec : analyzedSpec} onEvent={handleEvent} />
    </div>
  );
};
