name: setup node
description: setup node

runs:
  using: composite
  steps:
    - name: Get versions
      id: version
      shell: bash
      run: |
        node_version=$(cat .tool-versions | grep nodejs | awk '{print $2}')
        pnpm_version=$(cat .tool-versions | grep pnpm | awk '{print $2}')
        echo "NODE_VERSION=$node_version" >> $GITHUB_OUTPUT
        echo "PNPM_VERSION=$pnpm_version" >> $GITHUB_OUTPUT

    - name: Install pnpm
      uses: pnpm/action-setup@v6
      with:
        version: ${{ steps.version.outputs.PNPM_VERSION }}

    - name: Use Node.js ${{ steps.version.outputs.NODE_VERSION }}
      uses: actions/setup-node@v7
      with:
        node-version: ${{ steps.version.outputs.NODE_VERSION }}
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
