name: Publish Package

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup node
        uses: ./.github/actions/setup_node

      - run: make lint
      - run: make typecheck
      - run: make test
      - run: make build
      - run: npm publish
